### ISSUE TITLE
CSS tooltips as an alternative (or replacement) for JS tooltips

### ISSUE THREAD

**Issue by cloudRoutine** [tpetricek/FSharp.Formatting#422]
CSS tooltips would make snippets generated by FSharp.Formatting usable in contexts where js execution is restricted. I think they would also simplify and cut down the size of the generated html pages

```html
<div>
  Let's pretend like this is src code</br>
</br>
<code> Array.<span class="tooltip ts mapfn" >map</span></code>
</div>
```
```css
.tooltip {
    position: relative;
    display: inline-block;
}

.tooltip.ts:hover::before{
  visibility: visible;
  border-style: solid;
  display: block;
  padding: 4px 8px;
  position: absolute;
  left: 0;
  bottom: 100%;
  white-space: pre;
  background-color: #000;
  color: #fff; 
}

.tooltip.ts.mapfn:hover::before { 
  content: 'you map arrays, \a what did you think? \a ;P';
}
```

![](http://i.imgur.com/OYurI7T.png)
_[(^ play with this example)](https://codepen.io/anon/pen/OXqVEm)_

the CSS pseudo classes make it easy to reuse tooltips at multiple points in the same snippet, and nothing as verbose as 
```html
<span onmouseout="hideTip(event, 'fs116', 445)" onmouseover="showTip(event, 'fs116', 445)" class="i">
```
would be needed anymore.

I'm no CSS expert, so there may be a more elegant way to implement this functionality.
